### ISSUE TITLE
Web isn't working properly on mobile 

### ISSUE THREAD

**Issue by RHL-RWT-01** [keizerworks/keizer-web#1]
![Screenshot_2024-10-29-19-00-28-86_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/31f00dbe-d8ed-4dfe-a87d-c4488552e125)

**Comment by aayushchugh** [comment]
We are redesigning the whole website, new version will work perfectly on a mobile screen.

Thanks for your feedback.
