### ISSUE TITLE
Can i change the site design and code structure?

### ISSUE THREAD

**Issue by zzzzshawn** [keizerworks/keizer-web#10]
About the design i was thinking of taking my own approach, Will keep the overlook look for the site but mabe change the aesthetic of the site.

Code structure:  Introduce some default ciolors  and font in tailwindconfig so people can your the same color scheme.

**Comment by Sudarsh1010** [comment]
We haven't finalized the colorscheme. for now using shadcn's default config. Please keep an eye on this project for upcoming issues. 
Thanks
