### ISSUE TITLE
Create a Sign in and Sign up page for keizer

### ISSUE THREAD

**Issue by Dishant1804** [keizerworks/keizer-web#11]
Aim to create a design that will attract the clients.

Design is somewhat like this :
![image](https://github.com/user-attachments/assets/5c6fc190-d8c8-4e62-915c-087d505f212f)

upon approval i'll link a PR to it. Open to make changes based on any other designs :)

**Comment by aayushchugh** [comment]
Thanks for your efforts but we don't need an authentication system because this website is static.
