### ISSUE TITLE
feat: enhance navbar ui  in mobile view

### ISSUE THREAD

**Issue by vamsi4845** [keizerworks/keizer-web#12]
Currently, the navbar isn't responsive  and overlaps the logo in the mobile view,Fixed that and attached the video below

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>
      <video src="https://github.com/user-attachments/assets/435b336e-43dd-4032-b61e-8ae6c3abc7e2
" width="100%" controls></video>
    </td>
    <td>
      <video src="https://github.com/user-attachments/assets/2f413def-f0c9-4852-8a29-f61fe2efe9ce
" width="100%" controls></video>
    </td>
  </tr>
</table>

**Comment by Sudarsh1010** [comment]
Hey @vamsi4845 
Thanks for the contribution. can you add another video of tablet resolution?

**Comment by vamsi4845** [comment]
> Hey @vamsi4845 Thanks for the contribution. can you add another video of tablet resolution?

I've fixed the mobile view only for now lemme try the tab view too

**Comment by Sudarsh1010** [comment]
it's fine just add padding, get start button is closer to the right edge of the screen. padding should be same from screen for both logo and get started button

**Comment by vamsi4845** [comment]
> it's fine just add padding, get start button is closer to the right edge of the screen. padding should be same from screen for both logo and get started button
The issue is with the logo basically, it has fixed dimensions thatsy padding looks  different

https://github.com/user-attachments/assets/731a71d6-0734-4d90-aec3-596f9eea810e

What do u want me to do now?

**Comment by Sudarsh1010** [comment]
yeah raise the pr

**Comment by vamsi4845** [comment]
> yeah raise the pr

Ok
