### ISSUE TITLE
chore: create issue templates

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/keizer-web#14]
Reference: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by pavanydg** [comment]
@aayushchugh i would like to work on this

**Comment by aayushchugh** [comment]
@pavanydg you can pick this one.

We need issue templates for feature requests, bugs and an option to create empty issue

**Comment by pavanydg** [comment]
@aayushchugh should i add default issue template or add issue forms.

**Comment by aayushchugh** [comment]
@pavanydg please add issue forms.
