### ISSUE TITLE
[CHORE] 🔢 Primary Color Overwrite in Tailwind Config

### ISSUE THREAD

**Issue by Sudarsh1010** [keizerworks/keizer-web#24]
### Description

The primary color is currently set in the Tailwind config, which overwrites the intended HSL value in globals.css. This leads to inconsistencies and makes it challenging to manage the color in one centralized location.

### Are you willing to submit PR?

No

**Comment by aakash0602** [comment]
can i work on this

**Comment by Sudarsh1010** [comment]
Assigning @aakash0602
