### ISSUE TITLE
"Feature: New Component Highlighting Keizer's Top Company Collaborations

### ISSUE THREAD

**Issue by subediaakash** [keizerworks/keizer-web#27]
### Description

HI @Sudarsh1010 
I've just completed adding the section featuring the top companies that Keizer has worked with, and I'm excited to share my progress with you.

I've ensured no overlap with the Hero component (since another team member is currently handling it), and instead, I created a new component focused solely on the client-side aspects. This structure keeps our workflow organized and modular.

After reviewing the final result, I believe this component adds great value, showcasing Keizer's affiliations effectively. If everything looks good on your end, please let me know so I can go ahead and create a pull request.

I've also raised an issue for documentation, in case any future updates or adjustments are needed. I’d love your feedback to ensure it aligns with our vision for this section!

Thanks in advance for reviewing my work—looking forward to any suggestions and next steps.

![image](https://github.com/user-attachments/assets/95487933-3bbc-4b47-ae9c-fe9810c44986)
![image](https://github.com/user-attachments/assets/8356ca1f-8761-43e0-b0d7-579033069e1b)

### Are you willing to submit PR?

Yes

**Comment by Sudarsh1010** [comment]
@subediaakash Thank you for the contribution.
please raise the PR. one of core member will review it.

**Comment by Sudarsh1010** [comment]
add @DMZTdhruv as reviewer for the PR

**Comment by subediaakash** [comment]
okay @Sudarsh1010  sir working on it

**Comment by DMZTdhruv** [comment]
hey thanks for the contribution, we are currently using those logos as the placeholder, and we have come to a conclusion of not to use it keep other content alright
summary: Remove logos haha

**Comment by subediaakash** [comment]
@DMZTdhruv  only the logo right sir ? the content part is okay right ?

**Comment by DMZTdhruv** [comment]
Yup @subediaakash !!!
just the content

**Comment by subediaakash** [comment]
Yes No worries @Sudarsh1010
