### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by ShyamSunder149** [keizerworks/keizer-web#3]
Found a few UI Issues  : 
 - footer is not organised properly
 - Works page doesn't have a footer
 - About us page UI needs some alignment 
 
 Enhancements : 
 - Send Inquiry button can be enabled if the privacy policy check box is ticked
 
Kindly let me know are these intended behaviour or not.

**Comment by rahulsainlll** [comment]
that was the old site in soon new site will launch that would be fine. if you see any changes need or issue kindly raise issue
