### ISSUE TITLE
[FEAT] :sparkles: Change selection color

### ISSUE THREAD

**Issue by aayushchugh** [keizerworks/keizer-web#35]
### Description

We should change the selection colour because the default one does not look good in other sections

![image](https://github.com/user-attachments/assets/a6472491-910b-4555-93f6-cbd870a56052)

![image](https://github.com/user-attachments/assets/8eef2cdc-8e9c-4c0e-923d-cc9dc4421826)

### Are you willing to submit PR?

No

**Comment by pavanydg** [comment]
![Screenshot from 2024-11-21 23-19-27](https://github.com/user-attachments/assets/e88a3b35-5829-48b9-aca5-49d743ce5002)
![Screenshot from 2024-11-21 23-19-04](https://github.com/user-attachments/assets/04663c59-4048-49a1-b62e-37709aae7f9e)
@aayushchugh is this selection color okay?

**Comment by aayushchugh** [comment]
Looks good!! Can you try black text on white background too?

**Comment by pavanydg** [comment]
![Screenshot from 2024-11-21 23-25-43](https://github.com/user-attachments/assets/d66aa4a5-3896-4a6b-8a83-ffbeb406fe28)
![Screenshot from 2024-11-21 23-25-31](https://github.com/user-attachments/assets/5415e4a3-d161-422b-b511-632d2f943380)
@aayushchugh?

**Comment by pavanydg** [comment]
@aayushchugh i like grey, since the website is dark themed.

**Comment by aayushchugh** [comment]
@pavanydg let's go with grey then
