### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by Sahoo999** [keizerworks/keizer-web#4]

**Comment by rahulsainlll** [comment]
kindle explain your to-do

**Comment by 4F24L** [comment]
@rahulsainlll  Why the deploy link isn't in the description ?!

**Comment by aayushchugh** [comment]
@4F24L This website is not ready yet and is under development

**Comment by Dishant1804** [comment]
@aayushchugh what is the next feature for this website?

**Comment by aayushchugh** [comment]
@Dishant1804 we are crating this website to showcase our products and services.

So we need those sections. I'll create a detailed list soon. We are busy due to diwali

**Comment by Sudarsh1010** [comment]
@aayushchugh should we close this issue?

**Comment by aayushchugh** [comment]
Yup
