### ISSUE TITLE
[FEAT] :sparkles: Responsive Navbar with Sidebar Toggle X

### ISSUE THREAD

**Issue by Arnab7456** [keizerworks/keizer-web#43]
### Description

Dynamic Sidebar Toggle:

The sidebar opens on clicking the hamburger menu (AlignJustify icon) and closes on clicking the X icon.

my solution is 

![Screenshot 2024-12-07 130533](https://github.com/user-attachments/assets/b3c48cf6-0568-4290-8c4b-4f59a331948c)
![Screenshot 2024-12-07 130316](https://github.com/user-attachments/assets/77308ba9-23be-4cad-ae3b-73af0e6e12b2)

This implementation improves user experience on smaller devices, making the navigation system more intuitive and responsive.

### Are you willing to submit PR?

Yes

**Comment by sanatan-dive** [comment]
so we have to replace hamburger menu when opened with an X icon??

**Comment by Arnab7456** [comment]
I have already raised the PR, so I don't need to work on that issue.
