### ISSUE TITLE
[BUG] :bug: Implement Core Performance Optimizations

### ISSUE THREAD

**Issue by ashutosh-rath02** [keizerworks/keizer-web#48]
### Current Behaviour

Slow initial page load
Images load abruptly
Sluggish scrolling performance

### Expected Behaviour

Faster initial page load
Progressive image loading with placeholders
Smooth scrolling experience

### Steps To Reproduce

Open website in Chrome
Open DevTools then Performance tab
Enable Mobile throttling and 4x CPU slowdown
Record page load and scroll interaction
Observe performance issues in timeline

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Chrome
- version: latest
```

### Anything else?

I would like to work on it😀

### Are you willing to submit PR?

Yes

**Comment by Sudarsh1010** [comment]
![image](https://github.com/user-attachments/assets/873f55a5-84e9-432a-8855-1abd12290473)
![image](https://github.com/user-attachments/assets/f7f7f014-e8e8-4a14-bf15-437e26a647c4)
I guess we have good score. for now we won't be proceeding with this. 
but yeah, In future we definitely gonna work on this.
Thank You

**Comment by Sudarsh1010** [comment]
and please refer pinned comment
